### ISSUE TITLE
[FEATURE] MacOS Catalina support

### ISSUE THREAD

**Issue by stefankuksenko** [markdwags/Razor#129]
I play on UO Renaissance server on MacOS Catalina OS using Classic UO.
Tried to add Razor plugin to ClassicUO and got an error. 
Is it possible to use Razor on MacOS with ClassicUO ?
If it is not possible please clarify do you have a plan to add MacOS Support?

**Comment by markdwags** [comment]
Razor on Mac could happen but you first need need a developer whos primary platform is Mac.  From there, either they need SDL2 built for 32bit so you can run classicuo with mono ClassicUO.exe --arch=32 or needs someone to take one of these forks of Mono's System.Windows.Forms that work/wip on x64 not only 32bit like stock System.Windows.Forms does on Mac.

Alternatively, Razor would need to be re-written using a cross platform UI framework.  No plans for that at the moment due to the time required.

**Comment by ray77** [comment]
> Razor on Mac could happen but you first need need a developer whos primary platform is Mac. From there, either they need SDL2 built for 32bit so you can run classicuo with mono ClassicUO.exe --arch=32 or needs someone to take one of these forks of Mono's System.Windows.Forms that work/wip on x64 not only 32bit like stock System.Windows.Forms does on Mac.

Like this:
https://github.com/emclient/mac-playground
64Bit Cocoa WinForms

**Comment by vladimir-aubrecht** [comment]
Hi 😊 After 20 years I got back to UO and looking also for MacOS support for Razor 😊 Did anything change since 2020? Is UI Framework and time required to rewrite/adopt it only blocker?
