### ISSUE TITLE
can it connect to Electronic Arts/Origin Servers ?

### ISSUE THREAD

**Issue by ice-domain** [markdwags/razor#231]
I'm very early player, AKF for a long time ,  now I'm back.
I found this new versions .
If it can be connect EA Origin Servers ,How do I set up ?

**Comment by kamronbatman** [comment]
Should work.

**Comment by BrokeUOplayer** [comment]
> Should work.

Well it doesn't, and you input was pointless! I have been trying all morning, launcher does not work, when I try to add the plugin for razor, the program just closes. I had razor version 1.0.7 XYZ and it worked flawlessly, this new version 1.9 xyz is crap and will not find OSI server. There are NO current help forums for this new version and how to even set it up on OSI server!

**Comment by kamronbatman** [comment]
The program just closes cause the EA client is a 32bit program. Try the x86 razor, not the x64 and see if you have better luck.

**Comment by BrokeUOplayer** [comment]
Thx, that worked. I had to do a fresh install of UO and Razor because my computer died. The launcher interface is definitely different, I never used it before. Thx for the help. Sent from my iPhoneOn Jun 20, 2024, at 11:58 AM, Kamron Batman ***@***.***> wrote:﻿
The program just closes cause the EA client is a 32bit program. Try the x86 razor, not the x64 and see if you have better luck.
