### ISSUE TITLE
ClassicUO Casting Chivalry From Chivalry Book

### ISSUE THREAD

**Issue by Kalan-Brock** [markdwags/Razor#82]
This only happens when using chivalry from a book, rather than a hotkey.  The people on their Discord said this is a Razor issue.

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Assistant.PacketHandlers.ExtendedClientCommand(Packet p, PacketHandlerEventArgs args)
   at Assistant.PacketHandler.ProcessFilters(List`1 list, Packet p)

**Comment by Meireffer** [comment]
New Razor? With scripting? If yes then it also happens when you try to use Spellweaving spells or Bushido spells, either by clicking in book or shortcut dragged from book to your screen.
Same thing happens when you create macro in CUO (CastSpell) and try to use Chiv/SW/Bushido (most likely Misticism aswell - didnt try). 
Casting those spells from Razor hotkeys work fine.

Using those spells without launched Razor does not trigger this error, so it's not CUO issue.

I did check it on previous version of Razor (pre-scripting) and it was working fine. Problems started on new version.

**Comment by comiluv** [comment]
I'm getting this as well. Also happens with Spellweaving, Bushido and Ninjitsu spells
Does not happen with Magery, Necromancy, Mysticism spells.
